(() => {
  'use strict';
  const state = { screen: 'home', videos: [], fireVideos: [], events: [], selectedFire: null, job: null, poll: null };
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function json(url, opts) { const r = await fetch(url, opts); const b = await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error || `HTTP ${r.status}`); return b; }
  function injectStyle() {
    if (document.getElementById('atomic-demo-style')) return;
    const s=document.createElement('style'); s.id='atomic-demo-style'; s.textContent=`
#atomic-demo-root{position:fixed;inset:0 0 0 265px;background:#090c12;color:#f4f6fb;z-index:8000;overflow:auto;padding:30px;font-family:inherit}.atomic-demo-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:24px}.atomic-demo-head h1{font-size:28px;margin:0}.atomic-back,.atomic-btn{border:1px solid #2a3040;background:#151a25;color:#fff;border-radius:10px;padding:10px 15px;cursor:pointer}.atomic-btn.primary{background:#665cf6;border-color:#665cf6}.atomic-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:18px}.atomic-card{background:#121722;border:1px solid #242b3a;border-radius:16px;padding:18px;cursor:pointer;min-height:125px}.atomic-card h3{margin:8px 0}.atomic-card p,.atomic-muted{color:#9ca5b7}.atomic-video-card video{width:100%;aspect-ratio:16/9;background:#000;border-radius:10px;object-fit:cover}.atomic-tabs{display:flex;gap:10px;margin:0 0 20px}.atomic-tabs button{border:1px solid #2a3040;background:#151a25;color:#aeb5c4;padding:10px 16px;border-radius:10px;cursor:pointer}.atomic-tabs button.active{background:#665cf6;color:#fff}.atomic-event img{width:100%;aspect-ratio:16/10;object-fit:cover;border-radius:10px}.atomic-status{margin:14px 0;padding:12px 14px;border:1px solid #293044;border-radius:10px;background:#111620}.atomic-modal{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:9000;display:flex;align-items:center;justify-content:center;padding:30px}.atomic-modal-box{width:min(1000px,92vw);background:#10141e;border:1px solid #2a3040;border-radius:16px;overflow:hidden}.atomic-modal-head{display:flex;justify-content:space-between;align-items:center;padding:16px 20px}.atomic-modal-head button{font-size:25px;background:none;border:0;color:white;cursor:pointer}.atomic-modal video{width:100%;max-height:75vh;background:#000;display:block}@media(max-width:850px){#atomic-demo-root{left:0;padding:18px}.atomic-grid{grid-template-columns:1fr}}
`; document.head.appendChild(s);
  }
  function root() { let r=document.getElementById('atomic-demo-root'); if(!r){r=document.createElement('section');r.id='atomic-demo-root';document.body.appendChild(r)} return r; }
  function closeDemo(){ document.getElementById('atomic-demo-root')?.remove(); clearInterval(state.poll); state.poll=null; }
  function header(title, back){return `<div class="atomic-demo-head"><div><h1>${esc(title)}</h1><div class="atomic-muted">Atomic Vision demonstration</div></div>${back?'<button class="atomic-back" data-demo-back>← Back</button>':'<button class="atomic-back" data-demo-close>Close</button>'}</div>`}
  async function renderHome(){state.screen='home';root().innerHTML=header('Demo',false)+`<div class="atomic-grid"><div class="atomic-card" data-demo-videos><h3>▶ Demo Videos</h3><p>Browse your demo videos and play any video in a popup.</p></div><div class="atomic-card" data-demo-fire><h3>🔥 Live Fire Detection</h3><p>Select a fire demo video, run NPU detection, and review detected events.</p></div></div>`;bind();}
  async function renderVideos(){state.screen='videos';state.videos=await json('/api/demo/videos');root().innerHTML=header('Demo Videos',true)+(state.videos.length?`<div class="atomic-grid">${state.videos.map(v=>`<div class="atomic-card atomic-video-card" data-play="${esc(v.url)}" data-name="${esc(v.name)}"><video src="${esc(v.url)}" muted preload="metadata"></video><h3>${esc(v.name)}</h3><p>Click to play</p></div>`).join('')}</div>`:`<div class="atomic-status">No demo videos yet. Put video files in <b>face_recognition/demo_media/videos/</b>.</div>`);bind();}
  async function renderFire(tab='detect'){state.screen='fire';[state.fireVideos,state.events]=await Promise.all([json('/api/demo/fire/videos'),json('/api/demo/fire/events')]);root().innerHTML=header('Live Fire Detection',true)+`<div class="atomic-tabs"><button data-fire-tab="detect" class="${tab==='detect'?'active':''}">Fire Detection</button><button data-fire-tab="events" class="${tab==='events'?'active':''}">Events (${state.events.length})</button></div>${tab==='events'?eventsHTML():fireHTML()}`;bind();}
  function fireHTML(){return `${state.job?`<div class="atomic-status"><b>Status:</b> ${esc(state.job.status)} &nbsp; <b>Progress:</b> ${Number(state.job.progress||0)}%${state.job.error?`<br>${esc(state.job.error)}`:''}</div>`:''}${state.fireVideos.length?`<div class="atomic-grid">${state.fireVideos.map(v=>`<div class="atomic-card atomic-video-card" data-fire-video="${esc(v.name)}"><video src="${esc(v.url)}" muted preload="metadata"></video><h3>${esc(v.name)}</h3><p>${state.selectedFire===v.name?'Selected':'Click to select'}</p>${state.selectedFire===v.name?'<button class="atomic-btn primary" data-start-fire>Start Detection</button>':''}</div>`).join('')}</div>`:`<div class="atomic-status">No fire videos yet. Put videos in <b>face_recognition/demo_media/fire_videos/</b>.</div>`}`}
  function eventsHTML(){if(!state.events.length)return '<div class="atomic-status">No fire/smoke events detected yet.</div>';return `<div class="atomic-grid">${state.events.map(e=>{const d=new Date(e.timestamp);return `<div class="atomic-card atomic-event"><img src="${esc(e.image_url)}"><h3>${esc(String(e.label||'fire').toUpperCase())}</h3><p>${esc(e.video||'')}</p><p>${esc(d.toLocaleDateString())} • ${esc(d.toLocaleTimeString())}</p></div>`}).join('')}</div>`}
  function openVideo(url,name){const m=document.createElement('div');m.className='atomic-modal';m.id='atomic-demo-modal';m.innerHTML=`<div class="atomic-modal-box"><div class="atomic-modal-head"><b>${esc(name)}</b><button data-modal-close>×</button></div><video src="${esc(url)}" controls autoplay></video></div>`;document.body.appendChild(m);m.querySelector('[data-modal-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};}
  async function startFire(){if(!state.selectedFire)return;state.job=await json('/api/demo/fire/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video:state.selectedFire})});await renderFire('detect');clearInterval(state.poll);state.poll=setInterval(async()=>{try{state.job=await json(`/api/demo/fire/jobs/${encodeURIComponent(state.job.id)}`);await renderFire('detect');if(['completed','error'].includes(state.job.status)){clearInterval(state.poll);state.poll=null;}}catch(e){}},1000);}
  function bind(){const r=root();r.querySelector('[data-demo-close]')?.addEventListener('click',closeDemo);r.querySelector('[data-demo-back]')?.addEventListener('click',()=>state.screen==='fire'||state.screen==='videos'?renderHome():renderHome());r.querySelector('[data-demo-videos]')?.addEventListener('click',renderVideos);r.querySelector('[data-demo-fire]')?.addEventListener('click',()=>renderFire('detect'));r.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>openVideo(x.dataset.play,x.dataset.name));r.querySelectorAll('[data-fire-video]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-start-fire]'))return;state.selectedFire=x.dataset.fireVideo;renderFire('detect')});r.querySelector('[data-start-fire]')?.addEventListener('click',e=>{e.stopPropagation();startFire()});r.querySelectorAll('[data-fire-tab]').forEach(x=>x.onclick=()=>renderFire(x.dataset.fireTab));}
  function findSettings(){return [...document.querySelectorAll('a,button,[role="button"],li')].find(x=>x.textContent.trim()==='Settings');}
  function installNav(){if(document.querySelector('[data-atomic-demo-nav]'))return;const settings=findSettings();if(!settings)return;const item=settings.cloneNode(true);item.dataset.atomicDemoNav='1';item.removeAttribute('href');item.querySelectorAll('[id]').forEach(x=>x.removeAttribute('id'));const walker=document.createTreeWalker(item,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.nodeValue.trim()==='Settings')n.nodeValue=n.nodeValue.replace('Settings','Demo')}item.style.cursor='pointer';item.onclick=e=>{e.preventDefault();e.stopPropagation();injectStyle();renderHome()};settings.parentNode.insertBefore(item,settings.nextSibling);}
  injectStyle();installNav();new MutationObserver(installNav).observe(document.documentElement,{childList:true,subtree:true});
})();
