const express = require('express');

const previousSend = express.response.send;

// FontAwesome is intentionally unavailable in the offline/LAN build.  The
// existing offlineAssetsHook handles the common static icons, while this hook
// handles every FontAwesome icon dynamically generated by app.js as well.
const iconMap = {
  'fa-brain-circuit': '⚛',
  'fa-video': '▶',
  'fa-video-slash': '⊘',
  'fa-users-gear': '⚙',
  'fa-users-slash': '♙',
  'fa-user': '♙',
  'fa-user-plus': '♙+',
  'fa-folder-open': '▣',
  'fa-wand-magic-sparkles': '✦',
  'fa-sliders': '☷',
  'fa-camera': '◉',
  'fa-trash-can': '×',
  'fa-square-plus': '+',
  'fa-ellipsis-vertical': '⋮',
  'fa-circle-check': '✓',
  'fa-circle-exclamation': '!',
  'fa-bell-slash': '○',
  'fa-chevron-left': '‹',
  'fa-chevron-right': '›',
  'fa-xmark': '×',
  'fa-magnifying-glass': '⌕',
  'fa-cloud-arrow-up': '↑',
  'fa-image': '▧',
  'fa-images': '▧',
  'fa-circle-info': 'ⓘ',
  'fa-floppy-disk': '▣',
  'fa-network-wired': '⌁',
  'fa-file-video': '▷',
  'fa-circle': '●',
  'fa-check': '✓',
  'fa-plus': '+',
  'fa-minus': '−',
  'fa-play': '▶',
  'fa-pause': 'Ⅱ',
  'fa-stop': '■',
  'fa-arrow-left': '←',
  'fa-arrow-right': '→',
  'fa-download': '↓',
  'fa-upload': '↑',
  'fa-refresh': '↻',
  'fa-arrows-rotate': '↻',
  'fa-house': '⌂',
  'fa-chart-line': '↗',
  'fa-database': '◉',
  'fa-gear': '⚙',
  'fa-cog': '⚙',
  'fa-camera-retro': '◉',
  'fa-circle-xmark': '×',
  'fa-triangle-exclamation': '!',
  'fa-circle-question': '?',
  'fa-info': 'i',
  'fa-eye': '◉',
  'fa-eye-slash': '⊘',
  'fa-link': '↗',
  'fa-link-slash': '×',
  'fa-expand': '↗',
  'fa-compress': '↙',
  'fa-bars': '☰',
  'fa-filter': '≡',
  'fa-calendar': '□',
  'fa-clock': '◷',
  'fa-spinner': '◌',
  'fa-circle-notch': '◌'
};

const fallbackCss = `<style id="atomic-offline-icon-fix">
  i[class*="fa-"] {
    font-family: "Segoe UI Symbol", "Noto Sans Symbols 2", "Noto Sans Symbols", Arial, sans-serif !important;
    font-style: normal !important;
    font-weight: 400 !important;
    display: inline-flex !important;
    align-items: center !important;
    justify-content: center !important;
    min-width: 1em !important;
    width: 1.15em !important;
    height: 1.15em !important;
    line-height: 1 !important;
    text-align: center !important;
    vertical-align: middle !important;
    speak: never !important;
  }
  i.atomic-offline-icon::before {
    content: attr(data-offline-icon) !important;
    font-family: "Segoe UI Symbol", "Noto Sans Symbols 2", "Noto Sans Symbols", Arial, sans-serif !important;
    font-style: normal !important;
    font-weight: 400 !important;
    opacity: 1 !important;
    visibility: visible !important;
    display: inline-block !important;
  }
</style>`;

const script = `<script id="atomic-offline-icon-script">
(() => {
  const map = ${JSON.stringify(iconMap)};
  const apply = (root = document) => {
    root.querySelectorAll?.('i[class*="fa-"]').forEach((el) => {
      if (el.classList.contains('atomic-offline-icon')) return;
      const classes = [...el.classList];
      let glyph = null;
      for (const cls of classes) {
        if (map[cls]) { glyph = map[cls]; break; }
      }
      // Guarantee that an unknown FontAwesome class is never blank offline.
      if (!glyph) glyph = '•';
      el.dataset.offlineIcon = glyph;
      el.classList.add('atomic-offline-icon');
      el.setAttribute('aria-hidden', 'true');
    });
  };
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => apply());
  } else {
    apply();
  }
  new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === 1) apply(node);
      });
    }
  }).observe(document.documentElement, { childList: true, subtree: true });
})();
</script>`;

express.response.send = function atomicOfflineIconSend(body) {
  if (typeof body === 'string' && /<html[\s>]/i.test(body)) {
    if (!body.includes('id="atomic-offline-icon-fix"')) {
      body = body.replace('</head>', `${fallbackCss}\n</head>`);
    }
    if (!body.includes('id="atomic-offline-icon-script"')) {
      body = body.replace('</body>', `${script}\n</body>`);
    }
  }
  return previousSend.call(this, body);
};

console.log('[Offline] Dynamic FontAwesome icons now have local fallbacks.');
